/**
 * GenerateCommand - Scaffold new project resources via CLI
 *
 * Provides generators for creating boilerplate files from templates:
 *   generate worker <name>  - Create a new worker YAML + expertise markdown
 *
 * The `--type` flag selects a preset template (default, gpu, lightweight).
 * Generated files are placed in the standard project directories:
 *   workers/<name>.yml      - Worker configuration
 *   expertise/<name>.md     - Worker expertise / soul file
 *
 * @module cli/GenerateCommand
 */

import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Custom error for generate command failures
 */
export class GenerateCommandError extends Error {
  /**
   * Create a GenerateCommandError
   * @param {string} message - Error message
   * @param {Object} [options={}] - Error options
   * @param {Error} [options.cause] - Original error that caused this error
   * @param {string} [options.operation] - The operation that failed
   * @param {string} [options.resourceName] - Name of the resource being generated
   */
  constructor(message, options = {}) {
    super(message, { cause: options.cause });
    this.name = 'GenerateCommandError';
    this.operation = options.operation;
    this.resourceName = options.resourceName;
  }
}

// =============================================================================
// Worker type presets
// =============================================================================

/**
 * Preset configurations for different worker types
 * @type {Object<string, Object>}
 */
const WORKER_PRESETS = Object.freeze({
  default: {
    description: 'A general-purpose worker',
    container: { image: 'ai-army/worker:latest', cpus: 2, memory: '4g' },
    tools: ['bash', 'git', 'readFile', 'writeFile'],
    replicas: 1,
  },
  gpu: {
    description: 'A GPU-accelerated worker for ML/AI tasks',
    container: { image: 'ai-army/worker-gpu:latest', cpus: 4, memory: '16g' },
    tools: ['bash', 'git', 'readFile', 'writeFile'],
    replicas: 1,
  },
  lightweight: {
    description: 'A lightweight worker for simple tasks',
    container: { image: 'ai-army/worker:latest', cpus: 1, memory: '1g' },
    tools: ['bash', 'readFile'],
    replicas: 1,
  },
});

/**
 * Valid worker type names
 * @type {string[]}
 */
const VALID_TYPES = Object.keys(WORKER_PRESETS);

// =============================================================================
// Template generation
// =============================================================================

/**
 * Generate worker YAML content from a preset
 *
 * @param {string} name - Worker ID / name
 * @param {string} type - Preset type ('default' | 'gpu' | 'lightweight')
 * @returns {string} YAML content for workers/<name>.yml
 * @private
 */
function generateWorkerYaml(name, type) {
  const preset = WORKER_PRESETS[type];
  const toolsList = preset.tools.map(t => `  - ${t}`).join('\n');

  return `# Worker: ${name}
# Type: ${type}
# Generated by ai-army generate worker

id: ${name}
name: ${formatName(name)}
description: ${preset.description}

# Expertise / soul file
expertise:
  file: expertise/${name}.md

# Repository (update with your repo)
repo:
  url: git@github.com:your-org/your-repo.git
  branch: main

# Container configuration
container:
  image: ${preset.container.image}
  cpus: ${preset.container.cpus}
  memory: '${preset.container.memory}'

# Available tools
tools:
${toolsList}

# Deployment settings
deployment:
  server: vps-1
  replicas: ${preset.replicas}
  strategy: round-robin
  healthCheck:
    interval: 30
    timeout: 10
    retries: 3

enabled: true
`;
}

/**
 * Generate expertise markdown content
 *
 * @param {string} name - Worker ID / name
 * @param {string} type - Preset type
 * @returns {string} Markdown content for expertise/<name>.md
 * @private
 */
function generateExpertiseMd(name, type) {
  const displayName = formatName(name);
  const preset = WORKER_PRESETS[type];

  return `# ${displayName} — Expertise

You are ${displayName}, an AI worker running inside the AI Army framework.

## Role

${preset.description}. Your primary responsibilities include:

- Reading and understanding codebases
- Writing, editing, and refactoring code
- Running tests and fixing failures
- Answering technical questions

## Guidelines

1. **Be thorough** — Read existing code before making changes.
2. **Follow conventions** — Match the project's coding style and patterns.
3. **Test your work** — Run tests after making changes to verify correctness.
4. **Explain your reasoning** — When making decisions, explain why.
5. **Ask for clarification** — If requirements are ambiguous, ask before guessing.

## Constraints

- Do not commit secrets or credentials to version control.
- Do not run destructive commands without explicit confirmation.
- Stay within the scope of the assigned repository.
`;
}

/**
 * Format a kebab-case name into title case
 *
 * @param {string} name - kebab-case name (e.g., "my-worker")
 * @returns {string} Title case name (e.g., "My Worker")
 * @private
 */
function formatName(name) {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// =============================================================================
// Subcommand handler
// =============================================================================

/**
 * Generate a new worker from a type preset
 *
 * Creates workers/<name>.yml and expertise/<name>.md in the project directory.
 * Validates that the name is a valid kebab-case identifier and that the files
 * don't already exist.
 *
 * @param {Object} options - Command options
 * @param {string} options.name - Worker name (kebab-case, e.g., "my-worker")
 * @param {string} [options.type='default'] - Preset type
 * @param {string} [options.projectPath='.'] - Project root directory
 * @param {Function} options.write - Output writer function
 * @param {Object} [options.fs] - File system module (for DI/testing)
 * @returns {Promise<Object>} Result with success flag and file paths
 * @private
 */
async function generateWorker({
  name,
  type = 'default',
  projectPath = '.',
  write,
  fs: injectedFs,
}) {
  const fsModule = injectedFs || fs;

  if (!name) {
    throw new GenerateCommandError('Worker name is required', {
      operation: 'worker',
    });
  }

  // Validate name format (kebab-case: lowercase, dashes, digits)
  if (!/^[a-z][a-z0-9-]*$/.test(name)) {
    throw new GenerateCommandError(
      `Invalid worker name '${name}'. Use kebab-case (e.g., 'my-worker')`,
      { operation: 'worker', resourceName: name }
    );
  }

  // Validate type
  if (!VALID_TYPES.includes(type)) {
    throw new GenerateCommandError(
      `Invalid worker type '${type}'. Valid types: ${VALID_TYPES.join(', ')}`,
      { operation: 'worker', resourceName: name }
    );
  }

  const absPath = path.resolve(projectPath);
  const workerFile = path.join(absPath, 'workers', `${name}.yml`);
  const expertiseFile = path.join(absPath, 'expertise', `${name}.md`);

  // Check for existing files
  try {
    await fsModule.access(workerFile);
    throw new GenerateCommandError(`Worker file already exists: workers/${name}.yml`, {
      operation: 'worker',
      resourceName: name,
    });
  } catch (err) {
    if (err.name === 'GenerateCommandError') throw err;
    // File doesn't exist — good, continue
  }

  try {
    await fsModule.access(expertiseFile);
    throw new GenerateCommandError(`Expertise file already exists: expertise/${name}.md`, {
      operation: 'worker',
      resourceName: name,
    });
  } catch (err) {
    if (err.name === 'GenerateCommandError') throw err;
    // File doesn't exist — good, continue
  }

  // Ensure directories exist
  await fsModule.mkdir(path.join(absPath, 'workers'), { recursive: true });
  await fsModule.mkdir(path.join(absPath, 'expertise'), { recursive: true });

  // Generate and write files
  const workerContent = generateWorkerYaml(name, type);
  const expertiseContent = generateExpertiseMd(name, type);

  try {
    await fsModule.writeFile(workerFile, workerContent, 'utf8');
    await fsModule.writeFile(expertiseFile, expertiseContent, 'utf8');
  } catch (err) {
    throw new GenerateCommandError(`Failed to write files: ${err.message}`, {
      cause: err,
      operation: 'worker',
      resourceName: name,
    });
  }

  write(`✅ Generated worker '${name}' (type: ${type})\n`);
  write(`   📄 workers/${name}.yml\n`);
  write(`   📄 expertise/${name}.md\n`);
  write(`\nNext steps:\n`);
  write(`  1. Edit workers/${name}.yml to set your repo URL and deployment server\n`);
  write(`  2. Edit expertise/${name}.md to define the worker's personality\n`);
  write(`  3. Add 'workers/${name}.yml' to the workers list in ai-army.yml\n`);
  write(`  4. Run 'npx ai-army validate' to check your configuration\n`);

  return {
    success: true,
    name,
    type,
    files: {
      worker: workerFile,
      expertise: expertiseFile,
    },
  };
}

// =============================================================================
// Main entry point
// =============================================================================

/**
 * Run a generate subcommand
 *
 * Dispatches to the appropriate generator based on the `resource` argument.
 *
 * @param {string} resource - Resource type to generate ('worker')
 * @param {Object} [options={}] - Command options
 * @param {string} [options.name] - Name for the generated resource
 * @param {string} [options.type='default'] - Preset type for workers
 * @param {string} [options.projectPath='.'] - Project root directory
 * @param {Object} [options.output=process.stdout] - Writable stream for output
 * @param {Object} [options.fs] - File system module (for DI/testing)
 * @returns {Promise<Object>} Result with success flag and resource data
 * @throws {GenerateCommandError} If resource type is unknown
 */
export async function runGenerate(resource, options = {}) {
  const { output = process.stdout } = options;
  const write = msg => output.write(msg);

  const handlerOptions = { ...options, write };

  switch (resource) {
    case 'worker':
      return await generateWorker(handlerOptions);
    default:
      throw new GenerateCommandError(`Unknown resource type: '${resource}'. Valid types: worker`, {
        operation: resource,
      });
  }
}

export { WORKER_PRESETS, VALID_TYPES, generateWorkerYaml, generateExpertiseMd, formatName };
export default runGenerate;
