/**
 * GenerateCommand - Scaffold new project resources via CLI
 *
 * Provides generators for creating boilerplate files from templates:
 *   generate worker <name>  - Create a new worker YAML + expertise markdown
 *
 * The `--type` flag selects a preset template (default, gpu, lightweight).
 * Generated files are placed in the standard project directories:
 *   workers/<name>.yml      - Worker configuration
 *   expertise/<name>.md     - Worker expertise / soul file
 *
 * @module cli/GenerateCommand
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';
import { fileURLToPath } from 'node:url';

/**
 * Custom error for generate command failures
 */
export class GenerateCommandError extends Error {
  /**
   * Create a GenerateCommandError
   * @param {string} message - Error message
   * @param {Object} [options={}] - Error options
   * @param {Error} [options.cause] - Original error that caused this error
   * @param {string} [options.operation] - The operation that failed
   * @param {string} [options.resourceName] - Name of the resource being generated
   */
  constructor(message, options = {}) {
    super(message, { cause: options.cause });
    this.name = 'GenerateCommandError';
    this.operation = options.operation;
    this.resourceName = options.resourceName;
  }
}

// =============================================================================
// Worker template loading
// =============================================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Get the templates directory path
 * @returns {string} Absolute path to templates/workers
 * @private
 */
function getTemplatesDir() {
  // When installed globally: node_modules/ai-army/templates/workers
  // When in dev: <repo-root>/templates/workers
  return path.resolve(__dirname, '../../templates/workers');
}

/**
 * Load all available worker templates from templates/workers/*.yml
 * @param {Object} [fsModule=fs] - File system module (for DI/testing)
 * @returns {Promise<Object<string, Object>>} Map of type name to template config
 * @private
 */
async function loadWorkerTemplates(fsModule = fs) {
  const templatesDir = getTemplatesDir();
  let files;

  try {
    files = await fsModule.readdir(templatesDir);
  } catch (_err) {
    // Fallback to basic presets if templates dir not found
    return getFallbackPresets();
  }

  const templates = {};
  const yamlFiles = files.filter(f => f.endsWith('.yml') || f.endsWith('.yaml'));

  for (const file of yamlFiles) {
    const templatePath = path.join(templatesDir, file);
    try {
      const content = await fsModule.readFile(templatePath, 'utf8');
      const template = yaml.load(content);
      const type = path.basename(file, path.extname(file));
      templates[type] = template;
    } catch (_err) {
      // Skip invalid templates
      continue;
    }
  }

  // If no templates loaded, use fallback
  return Object.keys(templates).length > 0 ? templates : getFallbackPresets();
}

/**
 * Get fallback worker presets when templates can't be loaded
 * @returns {Object<string, Object>} Basic preset map
 * @private
 */
function getFallbackPresets() {
  return {
    default: {
      id: 'default',
      name: 'Default Worker',
      description: 'A general-purpose worker',
      container: { image: 'ai-army/worker:latest', cpus: 2, memory: '4g' },
      tools: ['bash', 'git', 'readFile', 'writeFile'],
      expertise: 'You are a general-purpose AI worker.',
      deployment: { replicas: 1 },
    },
  };
}

// =============================================================================
// Template generation
// =============================================================================

/**
 * Generate worker YAML content from a template
 *
 * @param {string} name - Worker ID / name
 * @param {Object} template - Template configuration object
 * @returns {string} YAML content for workers/<name>.yml
 * @private
 */
function generateWorkerYaml(name, template) {
  const toolsList = (template.tools || []).map(t => `  - ${t}`).join('\n');
  const mcpServers = (template.mcpServers || []).map(s => `  - ${s}`).join('\n');

  return `# Worker: ${name}
# Based on template: ${template.id || 'default'}
# Generated by ai-army generate worker

id: ${name}
name: ${formatName(name)}
description: ${template.description || 'A worker'}

# Expertise / soul file (customize in expertise/${name}.md)
expertise:
  file: expertise/${name}.md

# Repository (update with your repo)
repo:
  url: git@github.com:your-org/your-repo.git
  branch: main

# Container configuration
container:
  image: ${template.container?.image || 'ai-army/worker:latest'}
  cpus: ${template.container?.cpus || 2}
  memory: '${template.container?.memory || '4g'}'

# Available tools
tools:
${toolsList || '  - bash\n  - readFile\n  - writeFile'}

${mcpServers ? `# MCP servers\nmcpServers:\n${mcpServers}\n` : ''}
# Deployment settings
deployment:
  server: vps-1
  replicas: ${template.deployment?.replicas || 1}
  strategy: ${template.deployment?.strategy || 'round-robin'}
  healthCheck:
    interval: ${template.deployment?.healthCheck?.interval || 30}
    timeout: ${template.deployment?.healthCheck?.timeout || 10}
    retries: ${template.deployment?.healthCheck?.retries || 3}

enabled: true
`;
}

/**
 * Generate expertise markdown content from template
 *
 * @param {string} name - Worker ID / name
 * @param {Object} template - Template configuration object
 * @returns {string} Markdown content for expertise/<name>.md
 * @private
 */
function generateExpertiseMd(name, template) {
  const displayName = formatName(name);

  // If template has inline expertise, use it; otherwise generate basic
  if (template.expertise && typeof template.expertise === 'string') {
    return `# ${displayName} — Expertise

${template.expertise}

## Constraints

- Do not commit secrets or credentials to version control.
- Do not run destructive commands without explicit confirmation.
- Stay within the scope of the assigned repository.
`;
  }

  // Fallback generic expertise
  return `# ${displayName} — Expertise

You are ${displayName}, an AI worker running inside the AI Army framework.

## Role

${template.description || 'A general-purpose AI worker'}. Your primary responsibilities include:

- Reading and understanding codebases
- Writing, editing, and refactoring code
- Running tests and fixing failures
- Answering technical questions

## Guidelines

1. **Be thorough** — Read existing code before making changes.
2. **Follow conventions** — Match the project's coding style and patterns.
3. **Test your work** — Run tests after making changes to verify correctness.
4. **Explain your reasoning** — When making decisions, explain why.
5. **Ask for clarification** — If requirements are ambiguous, ask before guessing.

## Constraints

- Do not commit secrets or credentials to version control.
- Do not run destructive commands without explicit confirmation.
- Stay within the scope of the assigned repository.
`;
}

/**
 * Format a kebab-case name into title case
 *
 * @param {string} name - kebab-case name (e.g., "my-worker")
 * @returns {string} Title case name (e.g., "My Worker")
 * @private
 */
function formatName(name) {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// =============================================================================
// Subcommand handler
// =============================================================================

/**
 * Generate a new worker from a type preset
 *
 * Creates workers/<name>.yml and expertise/<name>.md in the project directory.
 * Validates that the name is a valid kebab-case identifier and that the files
 * don't already exist.
 *
 * @param {Object} options - Command options
 * @param {string} options.name - Worker name (kebab-case, e.g., "my-worker")
 * @param {string} [options.type='default'] - Preset type
 * @param {string} [options.projectPath='.'] - Project root directory
 * @param {Function} options.write - Output writer function
 * @param {Object} [options.fs] - File system module (for DI/testing)
 * @returns {Promise<Object>} Result with success flag and file paths
 * @private
 */
async function generateWorker({
  name,
  type = 'default',
  projectPath = '.',
  write,
  fs: injectedFs,
}) {
  const fsModule = injectedFs || fs;

  if (!name) {
    throw new GenerateCommandError('Worker name is required', {
      operation: 'worker',
    });
  }

  // Validate name format (kebab-case: lowercase, dashes, digits)
  if (!/^[a-z][a-z0-9-]*$/.test(name)) {
    throw new GenerateCommandError(
      `Invalid worker name '${name}'. Use kebab-case (e.g., 'my-worker')`,
      { operation: 'worker', resourceName: name }
    );
  }

  // Load available templates
  const templates = await loadWorkerTemplates(fsModule);
  const validTypes = Object.keys(templates);

  // Validate type
  if (!validTypes.includes(type)) {
    throw new GenerateCommandError(
      `Invalid worker type '${type}'. Valid types: ${validTypes.join(', ')}`,
      { operation: 'worker', resourceName: name }
    );
  }

  const template = templates[type];

  const absPath = path.resolve(projectPath);
  const workerFile = path.join(absPath, 'workers', `${name}.yml`);
  const expertiseFile = path.join(absPath, 'expertise', `${name}.md`);

  // Check for existing files
  try {
    await fsModule.access(workerFile);
    throw new GenerateCommandError(`Worker file already exists: workers/${name}.yml`, {
      operation: 'worker',
      resourceName: name,
    });
  } catch (err) {
    if (err.name === 'GenerateCommandError') throw err;
    // File doesn't exist — good, continue
  }

  try {
    await fsModule.access(expertiseFile);
    throw new GenerateCommandError(`Expertise file already exists: expertise/${name}.md`, {
      operation: 'worker',
      resourceName: name,
    });
  } catch (err) {
    if (err.name === 'GenerateCommandError') throw err;
    // File doesn't exist — good, continue
  }

  // Ensure directories exist
  await fsModule.mkdir(path.join(absPath, 'workers'), { recursive: true });
  await fsModule.mkdir(path.join(absPath, 'expertise'), { recursive: true });

  // Generate and write files
  const workerContent = generateWorkerYaml(name, template);
  const expertiseContent = generateExpertiseMd(name, template);

  try {
    await fsModule.writeFile(workerFile, workerContent, 'utf8');
    await fsModule.writeFile(expertiseFile, expertiseContent, 'utf8');
  } catch (err) {
    throw new GenerateCommandError(`Failed to write files: ${err.message}`, {
      cause: err,
      operation: 'worker',
      resourceName: name,
    });
  }

  write(`✅ Generated worker '${name}' (type: ${type})\n`);
  write(`   📄 workers/${name}.yml\n`);
  write(`   📄 expertise/${name}.md\n`);
  write(`\nNext steps:\n`);
  write(`  1. Edit workers/${name}.yml to set your repo URL and deployment server\n`);
  write(`  2. Edit expertise/${name}.md to define the worker's personality\n`);
  write(`  3. Add 'workers/${name}.yml' to the workers list in ai-army.yml\n`);
  write(`  4. Run 'npx ai-army validate' to check your configuration\n`);

  return {
    success: true,
    name,
    type,
    files: {
      worker: workerFile,
      expertise: expertiseFile,
    },
  };
}

// =============================================================================
// Main entry point
// =============================================================================

/**
 * Run a generate subcommand
 *
 * Dispatches to the appropriate generator based on the `resource` argument.
 *
 * @param {string} resource - Resource type to generate ('worker')
 * @param {Object} [options={}] - Command options
 * @param {string} [options.name] - Name for the generated resource
 * @param {string} [options.type='default'] - Preset type for workers
 * @param {string} [options.projectPath='.'] - Project root directory
 * @param {Object} [options.output=process.stdout] - Writable stream for output
 * @param {Object} [options.fs] - File system module (for DI/testing)
 * @returns {Promise<Object>} Result with success flag and resource data
 * @throws {GenerateCommandError} If resource type is unknown
 */
export async function runGenerate(resource, options = {}) {
  const { output = process.stdout } = options;
  const write = msg => output.write(msg);

  const handlerOptions = { ...options, write };

  switch (resource) {
    case 'worker':
      return await generateWorker(handlerOptions);
    default:
      throw new GenerateCommandError(`Unknown resource type: '${resource}'. Valid types: worker`, {
        operation: resource,
      });
  }
}

export {
  loadWorkerTemplates,
  getFallbackPresets,
  generateWorkerYaml,
  generateExpertiseMd,
  formatName,
  getTemplatesDir,
};
export default runGenerate;
